name: oneiros
base-image: ghcr.io/ublue-os/base-main
fedora-version: 38
description: A custom uBlue image. Make your own! https://universal-blue.org/tinker/make-your-own/
scripts:
  pre:
  - autorun.sh
  post:
  - autorun.sh
rpm:
  repos:
  - https://copr.fedorainfracloud.org/coprs/solopasha/hyprland/repo/fedora-%FEDORA_VERSION%/solopasha-hyprland-fedora-%FEDORA_VERSION%.repo
  - https://pkgs.tailscale.com/stable/fedora/tailscale.repo
  install:
  - adobe-source-code-pro-fonts
  - alacritty
  - brightnessctl
  - gnome-keyring
  - google-droid-sans-mono-fonts
  - google-noto-sans-fonts
  - google-go-mono-fonts
  - htop
  - hyprland
  - hyprpaper
  - ibm-plex-mono-fonts
  - jetbrains-mono-fonts-all
  - libadwaita
  - mozilla-fira-mono-fonts
  - neovim
  - pavucontrol
  - polkit-gnome
  - powerline-fonts
  - tailscale
  - thunar
  - thunar-archive-plugin
  - thunar-volman
  - waybar-hyprland
  - wofi
  - xdg-desktop-portal-hyprland
  - zsh
  remove:
  - firefox
  - firefox-langpacks
firstboot:
  yafti: false
  flatpaks:
  - com.discordapp.Discord
  - com.github.tchx84.Flatseal
  - com.github.zocker_160.SyncThingy
  - com.google.Chrome
  - com.obsproject.Studio
  - md.obsidian.Obsidian
